# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robin/projects/learning/c/tinyweb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robin/projects/learning/c/tinyweb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/projects/learning/c/tinyweb/CMakeFiles /home/robin/projects/learning/c/tinyweb/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/projects/learning/c/tinyweb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tinyweb

# Build rule for target.
tinyweb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyweb
.PHONY : tinyweb

# fast build rule for target.
tinyweb/fast:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/build
.PHONY : tinyweb/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

example/example_server.o: example/example_server.cpp.o

.PHONY : example/example_server.o

# target to build an object file
example/example_server.cpp.o:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example/example_server.cpp.o
.PHONY : example/example_server.cpp.o

example/example_server.i: example/example_server.cpp.i

.PHONY : example/example_server.i

# target to preprocess a source file
example/example_server.cpp.i:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example/example_server.cpp.i
.PHONY : example/example_server.cpp.i

example/example_server.s: example/example_server.cpp.s

.PHONY : example/example_server.s

# target to generate assembly for a file
example/example_server.cpp.s:
	$(MAKE) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example/example_server.cpp.s
.PHONY : example/example_server.cpp.s

src/connection.o: src/connection.cpp.o

.PHONY : src/connection.o

# target to build an object file
src/connection.cpp.o:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/connection.cpp.o
.PHONY : src/connection.cpp.o

src/connection.i: src/connection.cpp.i

.PHONY : src/connection.i

# target to preprocess a source file
src/connection.cpp.i:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/connection.cpp.i
.PHONY : src/connection.cpp.i

src/connection.s: src/connection.cpp.s

.PHONY : src/connection.s

# target to generate assembly for a file
src/connection.cpp.s:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/connection.cpp.s
.PHONY : src/connection.cpp.s

src/header.o: src/header.cpp.o

.PHONY : src/header.o

# target to build an object file
src/header.cpp.o:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/header.cpp.o
.PHONY : src/header.cpp.o

src/header.i: src/header.cpp.i

.PHONY : src/header.i

# target to preprocess a source file
src/header.cpp.i:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/header.cpp.i
.PHONY : src/header.cpp.i

src/header.s: src/header.cpp.s

.PHONY : src/header.s

# target to generate assembly for a file
src/header.cpp.s:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/header.cpp.s
.PHONY : src/header.cpp.s

src/methods.o: src/methods.cpp.o

.PHONY : src/methods.o

# target to build an object file
src/methods.cpp.o:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/methods.cpp.o
.PHONY : src/methods.cpp.o

src/methods.i: src/methods.cpp.i

.PHONY : src/methods.i

# target to preprocess a source file
src/methods.cpp.i:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/methods.cpp.i
.PHONY : src/methods.cpp.i

src/methods.s: src/methods.cpp.s

.PHONY : src/methods.s

# target to generate assembly for a file
src/methods.cpp.s:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/methods.cpp.s
.PHONY : src/methods.cpp.s

src/request.o: src/request.cpp.o

.PHONY : src/request.o

# target to build an object file
src/request.cpp.o:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/request.cpp.o
.PHONY : src/request.cpp.o

src/request.i: src/request.cpp.i

.PHONY : src/request.i

# target to preprocess a source file
src/request.cpp.i:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/request.cpp.i
.PHONY : src/request.cpp.i

src/request.s: src/request.cpp.s

.PHONY : src/request.s

# target to generate assembly for a file
src/request.cpp.s:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/request.cpp.s
.PHONY : src/request.cpp.s

src/response.o: src/response.cpp.o

.PHONY : src/response.o

# target to build an object file
src/response.cpp.o:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/response.cpp.o
.PHONY : src/response.cpp.o

src/response.i: src/response.cpp.i

.PHONY : src/response.i

# target to preprocess a source file
src/response.cpp.i:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/response.cpp.i
.PHONY : src/response.cpp.i

src/response.s: src/response.cpp.s

.PHONY : src/response.s

# target to generate assembly for a file
src/response.cpp.s:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/response.cpp.s
.PHONY : src/response.cpp.s

src/route.o: src/route.cpp.o

.PHONY : src/route.o

# target to build an object file
src/route.cpp.o:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/route.cpp.o
.PHONY : src/route.cpp.o

src/route.i: src/route.cpp.i

.PHONY : src/route.i

# target to preprocess a source file
src/route.cpp.i:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/route.cpp.i
.PHONY : src/route.cpp.i

src/route.s: src/route.cpp.s

.PHONY : src/route.s

# target to generate assembly for a file
src/route.cpp.s:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/route.cpp.s
.PHONY : src/route.cpp.s

src/server.o: src/server.cpp.o

.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) -f CMakeFiles/tinyweb.dir/build.make CMakeFiles/tinyweb.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tinyweb"
	@echo "... edit_cache"
	@echo "... example"
	@echo "... tests"
	@echo "... example/example_server.o"
	@echo "... example/example_server.i"
	@echo "... example/example_server.s"
	@echo "... src/connection.o"
	@echo "... src/connection.i"
	@echo "... src/connection.s"
	@echo "... src/header.o"
	@echo "... src/header.i"
	@echo "... src/header.s"
	@echo "... src/methods.o"
	@echo "... src/methods.i"
	@echo "... src/methods.s"
	@echo "... src/request.o"
	@echo "... src/request.i"
	@echo "... src/request.s"
	@echo "... src/response.o"
	@echo "... src/response.i"
	@echo "... src/response.s"
	@echo "... src/route.o"
	@echo "... src/route.i"
	@echo "... src/route.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

